### ISSUE TITLE
Fix api_views.forecast_data() to use proper accept type rather than 'format' query parameter

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#100]
- url(r'^forecast/(?P<forecast_pk>\d+)/data/$' : json, not csv: curl --header "Accept: text/csv" http://127.0.0.1:8000/api/forecast/3/data/
- also do for other API calls that can download in different formats - template, truth, etc.  <- Q: any of them support JSON, or are all CSV?
- temp.sh
- https://webmasters.stackexchange.com/questions/31212/difference-between-the-accept-and-content-type-http-headers
- http://www.django-rest-framework.org/api-guide/requests/#accepted_media_type
- http://www.django-rest-framework.org/api-guide/responses/#accepted_media_type
- https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
```
    # GET the data as CSV
    # - todo fix api_views.forecast_data() to use proper accept type rather than 'format' query parameter
    response = requests.get(data_uri,
                            headers={
                                # 'Accept': 'application/json; indent=4',
                                # 'Accept': 'text/csv',
                                'Authorization': 'JWT {}'.format(mo1_token),
                            },
                            params={'format': 'csv'},
                            )
```

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Technical debt.
