### ISSUE TITLE
Add scoring of date-based targets

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#102]
Currently we only score 'step-ahead' targets such as '1 wk ahead'. More generally we can score any continuous ones (e.g., 'Season peak percentage'). However, we should also score non-continuous ones like 'Season onset' or 'Season peak week'. @nickreich explained to me that this can get complicated. We think the solution is to add support for a fixed set of Zoltar-standard time representations, and use existing libraries like pymmwr to implement them. We'd probably use `Project.time_interval_type` for this.

This came up b/c these date-based targets - Season onset and Season peak week - currently have truth values (which were generated by abhinav's script) that have been converted from EWs to timezero dates. However, the predicted values are still EWs.

**Comment by nickreich** [comment]
Here is the start of a somewhat detailed proposal for date-based targets:

Target is defined as "date-based target" with accompanying "date format".
	`is_date == true`
	`date_format ==` [some unambiguous date in [strptime format](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html), e.g., "%Y%W%w"]
Then the `date_format` converts given values into a quantitative space. These values of the target are treated as a quantitative and discrete. 

Prediction types available to these kinds of targets:
 - point
 - binCat
 - sampleCat

How do we specify a range for such targets?
 - not season-specific: could pass a full sequence of acceptable dates or a start/end/increment.
 - season-specific: could pass a sequence of acceptable dates (or a start/end/increment) for each "season".

Validation:
 - every point prediction must be formattable by `date_format`
 - every cat in binCat or sampleCat prediction must be formattable by `date_format`
 - if range provided, every point prediction must in range
 - if range provided, every cat in binCat or sampleCat prediction must be in range

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
This is a long-term, complicated issue. I know @nickreich wants it done eventually. Prioritization is up to @nickreich .
