### ISSUE TITLE
Some visualizations still time out (application error)

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#128]
E.g., [Project visualizations for “CDC Flu challenge”](https://reichlab-forecast-repository.herokuapp.com/project/4/visualizations?season_name=2016-2017)

The culprit seems to be ` _model_id_to_location_timezero_points()`'s for loops

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Visualizations are currently disabled. Prioritization is up to @nickreich .
