### ISSUE TITLE
Visualization epiweek numbering differs from flusightnetwork.io

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#129]
Looking at the red arrows on the screen shot, you can see that for the same season and location, the second peak is located at two different epiweeks. Zoltar has it at EW5, but FSN is at EW6. Both sites do agree on the date (bottom line): 

![screen shot 2019-03-04 at 12 02 14 pm](https://user-images.githubusercontent.com/1034007/53749530-90073d00-3e75-11e9-8fdc-874d148c65ce.png): A bit after 'Feb 17'.

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Prioritization is up to @nickreich .
