### ISSUE TITLE
Cannot click "is public" checkbox in google chrome

### ISSUE THREAD

**Issue by katiehouse3** [reichlab/forecast-repository#135]
I am not able to uncheck the "is public" checkbox when creating a new project in Google Chrome (see screenshot below)
<img width="607" alt="Screen Shot 2019-04-19 at 11 06 56 AM" src="https://user-images.githubusercontent.com/26775314/56430166-7ee28600-6293-11e9-86d3-213c7049c7cf.png">

**Comment by matthewcornell** [comment]
Could not reproduce - worked on Mac Chrome Version 73.0.3683.103 . Please provide OS and browser version information. and specific steps to reproduce including the URL of project being edited. I don't have a Windows machine to debug with, so you might also need to include any javascript errors you see in the chrome developer log.

**Comment by matthewcornell** [comment]
@katiehouse3 what's the status of this?

**Comment by katiehouse3** [comment]
Turns out it was an outdated Google Chrome issue. This is good to close!
