### ISSUE TITLE
Repeated calls to get a project's models slows to a halt

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#140]
One or two return, then responses slow down and eventually hang. Happens regardless of client - R, Python, or web UI.

**Comment by Khoale1096** [comment]
With zoltpy repeating the call to Zoltar seems to work just fine. This piece of code that I used for pulling the names of all models in all projects give all 10 successful trials:
```
from zoltpy import util
conn = util.authenticate()
for i in range(10):
   for project in conn.projects:
     for model in project.models:
       print(model.name)
   print(str(i) + ' try')
```

**Comment by matthewcornell** [comment]
Thanks, Khoa. I think this verifies that previous optimizations have solved the issue. Closing.
