### ISSUE TITLE
Reduce time to download forecasts

### ISSUE THREAD

**Issue by katiehouse3** [reichlab/forecast-repository#148]
When Khoa and I were testing Zoltar, we noticed that our download_forecast() function took about 1 min and 06 seconds to find the forecast. Not 100% sure if this is on the Zoltpy side or the Zoltar side but we should try to reduce the time to download.

**Comment by matthewcornell** [comment]
Which forecast?
What's your code look like?
Have you tried direct GET calls from the command line vs. via zoltpy functions?
Is it always the same slowness, or are (for example) initial calls faster?
Have you tried other forecasts from this or other projects?

**Comment by matthewcornell** [comment]
Closing for now, after recent API changes.
