### ISSUE TITLE
project overview visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#149]
For a given project, could we create a heat-map visualization that would have rows as time-zeroes and columns as models and each cell of the matrix would represent whether a forecast is present for that particular model-timezero combination. Added bonus could be that a particular cell would be clickable and send you directly to the page of that specific forecast. But the utility of this overall would be to just show which models have forecasts for which times.

**Comment by matthewcornell** [comment]
A binary heat map like this is a cool idea that should not be difficult to implement. We essentially have that information now, albeit in a different form: Project detail pages show a table of time zeros, and the third column shows "# Forecasts", which is actually more information, but less convenient to parse than a matrix.

**Comment by matthewcornell** [comment]
@nick comments: Columns of a potential summary table for models:
model name
number of forecasts
first timezero
last timezero
number of units in most recent forecast
number of targets in most recent forecast (edited) 

extra bonus could be that the date for first/last timezero could be a link to that forecast

having table be sortable
