### ISSUE TITLE
scoring features

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#150]
- [ ] right now, the aggregate scores page just has MAE. can we make separate pages/tabs for different metrics? I.e. could we have a table for aggregate log-score as well?
- [ ] in the drop-down menu could we have an option to show the aggregate scores for the entire project, i.e. not a location-specific, but for all locations?

**Comment by matthewcornell** [comment]
Yes, both of those are possible.

**Comment by mzorn-58** [comment]
@nickreich @matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Aggregate scoring is currently disabled. Prioritization is up to @nickreich .
