### ISSUE TITLE
add initial data validations via project template

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#18]
- [x] add templates to projects
- [x] validate new forecasts against template - initial validations
- [x] validate template itself - initial validations

validations:
- correct number of bins
- each bin sums to zero
- for additional validations see #20

Estimate: 3

**Comment by matthewcornell** [comment]
@nickreich all that's left for bullet 2 is: "test points lie within the range of point values in the template". I don't have a handle on what this means. here's an example template and a file that might be compared to it:

- https://github.com/reichlab/forecast-repository/blob/master/forecast_app/tests/2016-2017_submission_template.csv
- https://github.com/reichlab/forecast-repository/blob/master/forecast_app/tests/EW1-KoTsarima-2017-01-17.csv

It would help if you could explain this to me :-)

**Comment by nickreich** [comment]
The thought was that for each target we could look at all of the values in the `point` rows for that target and would end up with a vector of numbers. The minimum and maximum of those numbers would define the acceptable range for the point values in the files themselves. E.g., if the predictions for target K should never be negative, then whoever made the template file would explicitly place a zero in at least one of the target K `point` rows. And none of those rows would have negative values. Is this too "cute" of a way to set the max/min ranges for testing? Alternatively, we could hard-code them as part of the project.

**Comment by matthewcornell** [comment]
Hi @nickreich . I have just finished implementing the following:

template tests:
- Template has no locations
- Target has no point value
- Target has no bins
- Target point and bin have different unit
- Target(s) was not found in every location
- Bin did not sum to 1.0


forecast tests:
- Locations did not match template
- Targets did not match template
- Bins did not match template
- Bin did not sum to 1.0
- Target unit not found or didn't match template


unimplemented forecast tests:
- test points lie within the range of point values in the template - see @nick's comment
- how important is the left handedness of the bins? by that i mean that bin_start_incl and bin_end_notincl - see @josh's comment

Question: How much more time should I spend on validation? We could defer these final tests so I could move on to other issues. FYI I emailed Juan to ask what tests his code does.

**Comment by nickreich** [comment]
Looks like a great start! I think it's ok to defer more validation to 
later and move on.
