### ISSUE TITLE
Visualization should not require truth

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#180]
We believe that currently it does not work unless truth values have been loaded into the project. Truth is needed for the "actual" line, but should be optional.

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
We've done no work on this, and visualization in Zoltar is on hold. I don't know what archiving an issue means - I'll punt to @nickreich .
