### ISSUE TITLE
migrate to target_type structure

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#182]
Full implementation of new target_type templates. This will require implementing the changes, as documented in [Target.md](https://github.com/reichlab/docs.zoltardata/blob/master/docs/Targets.md).

Some remaining questions that need resolution:
- [ ] can we resolve "is_step_ahead" and "step_ahead_increment" or require only 1?
- [ ] what is the appropriate format for "bin_range" parameter for date 
- [ ] for continuous targets and binLwrs, is infty needed in specification? 
- [ ] Is "point value type" still relevant or can we delete it?
- [ ] The language around "auto-created targets" needs to be clarified in the documentation.
- [ ] Need to write list of validations run for targets
- [ ] Need to finalize which scores are applied to which target types, esp for Brier and CRPS
- [ ] Define more clearly the relationship between BinLwrs and Range for continuous targets. Are both needed? Can we just require BinLwrs?
- [ ] what is "unit" for binary target type?

**Comment by nickreich** [comment]
I think #156 can be closed since we are working now on a more complete migration.

**Comment by matthewcornell** [comment]
https://github.com/reichlab/docs.zoltardata/blob/master/docs/Targets.md
https://github.com/reichlab/docs.zoltardata/blob/master/template-zoltar-project-config.JSON

**Comment by matthewcornell** [comment]
Regarding "auto-created targets", recall #111 . I believe this was a feature that extracted locations and targets from templates, but templates no longer exist, nor does this feature. The only place targets are now created is when loading a project config json file. We should:
[ ] remove references to it in the docs
[ ] change the project detail page to not highlight targets that are missing description and unit (two things at the time that auto-create could not fill in).

**Comment by matthewcornell** [comment]
@nickreich I do not see an example of a `Discrete` target in https://github.com/reichlab/docs.zoltardata/blob/master/template-zoltar-project-config.JSON . Would you please add one?

**Comment by nickreich** [comment]
Per convo with @matthewcornell, and addressing an item in the list at top of thread, consider removing `unit` field from binary target types.
