### ISSUE TITLE
Add interval scores for quantile predictions

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#196]
- [x] alpha = 0.2
- [x] additional alphas: 0.02, 0.05, 0.10, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90

**Comment by nickreich** [comment]
consider renaming scores so that they are `interval_20` instead of `interval_02` for alpha=.2. basically have the number be `alpha*100`.
