### ISSUE TITLE
Add ability to filter API results

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#199]
Users should be able to filter forecasts that they want to download. We need to specify what data is to be filterable (e.g., forecasts, scores, etc), and which fields can be operated on, and which operators are to be supported. @nickreich suggested:

```
"(forecasts for model m1 OR m2) AND location='l' AND target='t' AND timezero>`2020-05-08`"
```

The library functions should hide the back-and-forth process of creating a query, getting back a job, polling the job until finished, and then downloading the resulting data. They should see a command-line status bar as it waits.

**Comment by matthewcornell** [comment]
We'd also need to think about options for passing filter details to RESTful APIs. For example, to filter projects by name we might do: `GET /project/44?name="COVID-19 Forecasts"`. There are different ways to do this, each with pros/cons.

**Comment by matthewcornell** [comment]
Filtering scores is a little complicated because we cache score files, with all scores for each project in a separate file. To filter those we'd have to read the cached file back in, filter, and then return that version. Or something like that.

**Comment by matthewcornell** [comment]
Following up on this, for efficiency we will need to move forecast downloading from an immediate request to the server (which is what we do now - see my explanation below) to a queued request that gets run asynchronously by a worker. This means that users will need to do to multiple steps to download forecast data, like we do when uploading truth or forecast files:

1. initiate a request to the server for project forecast data, passing optional filters
2. immediately receive back from the server a Job object to be used for: a) tracking the status, and b) retrieving the final queried data
3. poll the job for status until it has succeeded
4. when successful, request the JSON data for the finished job

This complexity is necessary because, depending on the filter, we might be talking about millions of rows to process (every prediction in the project, if no filters are passed). This will take too long to run in the web process and so the task must be offloaded like we do when uploading truth or a forecast. We've gotten away with the simpler scheme of downloading in the web process until now because: a) users are only allowed to download one forecast at a time, and b) our forecasts have not been so large that the server times out. (A request that takes 30s or longer is killed by the underlying Heroku system, which is fair.)

I need to think about how the web UI will work with this scheme. For uploading forecasts, it's currently done like the libraries, that is, via a Job that you can poll (by refreshing the status page). Note that uploading truth is done immediately in the web process, something we might need to change depending on how big those files become. Unlike uploading forecasts, requesting a query will result in an S3 file that can be downloaded. I guess providing a downloadable link make the most sense.

(There is a question of how long the underlying results file - we use Amazon's S3 for file storage - should be kept. For example, I believe we could set up an S3 "bucket" policy for a time-based expiration, say 24 hours.)

**Comment by matthewcornell** [comment]
Current thinking about specifying the filters:

To filter a project's forecast data, we will support the following four types of filters. They are passed to the server as JSON:

1) Filter by *model*: pass zero or more model names (not abbreviations) in the `models` field. They are treated as "OR". Example:
```json
{"models": ["60-contact", "CovidIL_100"]}  # gets data from only these two models
```

2) Filter by *unit* or *target*: Pass zero or more names in the `units` or `targets` fields. Treated as "OR". Example:
```json
{"units": ["US"]}  # get data only for these this unit
{"targets": ["0 day ahead cum death", "100 day ahead cum death"]}  # get data only for these two targets
```

3) Filter by *timezero*: Pass zero one or two timezero dates in `yyyy-mm-dd` format in the `timezeros` field. The number passed determines how they are treated. Just one is treated as "EQUALS". Two are treated as "BETWEEN INCLUSIVE", i.e., only the timezeros that are between the two using <= are used. Example:

```json
{"timezeros": ["2020-04-01", "2020-04-30"]}  # get data only for April
```

4) Filter by forecast *type*: Pass a list of types in the `types` field. Choices are 'bin', 'named', 'point', 'sample', and 'quantile'. Treated as "OR". Example:
```json
{"types": ["point", "quantile"]}  # get only point and quantile data


The lists in 1, 2, 3, and 4 operate as "OR" on their own, but they are combined as "AND"s. Here's an example:

```json
{"models": ["60-contact", "CovidIL_100"],
 "units": ["US"],
 "targets": ["0 day ahead cum death", "100 day ahead cum death"],
 "timezeros": ["2020-04-01", "2020-04-30"],
 "types": ["point", "quantile"]
}
```
The results in data that's:
- (from either the '60-contact' OR 'CovidIL_100' models) AND
- (is unit 'US') AND
- (is either '0 day ahead cum death' or '100 day ahead cum death' target) AND
- ('2020-04-01' <= timezero <= '2020-04-30') AND (prediction type is either 'point' or 'quantile')

**Comment by nickreich** [comment]
The above query structure would be constrained to only return results from a given Zoltar project.

**Comment by nickreich** [comment]
I like the specification above, @matthewcornell . My one question is a front-end usability one, about how a user of zoltr or zoltpy can easily specify the list of desired timezeroes or models. we just want to make sure that the syntax for doing that isn't too cumbersome.

**Comment by matthewcornell** [comment]
@nickreich yes, that was what I was trying to get at with `Libraries will provide helper functions`. Here are some ideas:
- list of model names -> IDs
- "" unit names -> IDs
- "" target names -> IDs
- "" timezero_dates -> IDs
- 2-tuple of timezero_dates -> IDs between within that range
- ...

**Comment by matthewcornell** [comment]
Final design issue: what output format should we use for queries? Nick and I identified three options:

1. one predx-style csv file (tabular)
2. one json file per forecast, in the same format as our current json (grouped into a single zip file, for example)
3. one new json file in a new format, say a json list/array of #2.

The benefits of #1 are: it's a natural fit to what library users probably want, and it's simpler to code. The disadvantage is that the format is space-consuming (see the simple exploration below).

The benefits of #2: it might be straightforward to code, and it's more compact (again, see below). The disadvantages are that users have to use library functions to convert each json file to csv and them merge into a single table. Also, we have to deal with a zip file.

The benefits of #3: A single file (unlike #2), but it's a new format, and requires the same reassembly as #2.

Any thoughts? My current plan is to code #1 to see how it talks to me. If it flows, we'll try that to start, realizing we might have to change our minds if the size becomes untenable.


# Exploration of csv vs. json forecast file sizes

I looked briefly into how much of a size advantage our predx-inspired zoltar json format has over the input csv, and over the predx-style csv that can be created (zoltpy and zoltr) from the json. I picked the largest hub file I could find, with these results:

1. 2020-05-18-LANL-GrowthRate.csv - 15.9 MB
2. The corresponding JSON from https://www.zoltardata.com/forecast/10450 is 5.6 MB
3. The predx-style csv from the json is 11.5 MB

The json is about 3x smaller. The worst case scenario for size is an empty query, which means get every forecast row in the project. Working from above, let's say we have an average of: 12 MB/input file * 14 files/model (and growing) * 41 models = ~7 GB. That's #1 above (input files). #2 suggests ~1/3 that size for the json, say 2.5 GB. #3 might be a bit smaller than #1, maybe 5 GB?

WRT which format we choose for the "filter project forecasts" feature I'm coding, I'm still balancing ease-of-coding up a csv-based solution vs. a json-based one. Also, streaming rows into a CSV file is probably (much?) faster than processing rows and generating the JSON.

More as it develops. Thanks!

**Comment by matthewcornell** [comment]
A solution to users' asking for too many rows is to simply limit the number, failing the job if exceeded.
