### ISSUE TITLE
decide Django hosting requirements

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#2]
This is a planning issue to pick an initial Django host. Questions:

- How much are we willing to pay per month?
- How many users to we expect for our initial (e.g., alpha) deployment?
- How big a database (i.e., how many predictions) do we expect initially?

Once decided -> Create reichlab Heroku account w/credit card

**Comment by matthewcornell** [comment]
DEC: Heroku free tier

**Comment by matthewcornell** [comment]
My message to @nickreich :

OK, Best I can estimate from https://www.heroku.com/pricing , and having no database space statistics other than the prototype, and no runtime experience, I recommend we start with:

- *Dyno*: `Free tier` (limited to 1000 hours/month): $0/month. (Dynos are their units of computation.)
- *Postgres*: Start with: `Hobby > Basic` (limited to 10M rows): $9/month (good for maybe 10 models). If we need more: `Standard 0` (1 GB RAM, 64 GB storage, 120 connections): $50.00 (good for maybe 150 models)

NB: We will need to monitor to determine actual usage.

**Comment by nickreich** [comment]
sounds good to me.
