### ISSUE TITLE
some interval score calculations showing up as NA

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#201]
There are some missing scores for the DELPHI model, which should have all forecasts in place. Here is a sample of missing scores in Zoltar:
![image](https://user-images.githubusercontent.com/1280767/81824949-071d7400-9504-11ea-8f39-a47dafbcfbcc.png)

And here is the forecast to which those scores refer:
![image](https://user-images.githubusercontent.com/1280767/81825027-1a304400-9504-11ea-9ce2-c80703b3e279.png)

Is this an issue with the quantile floating points? I think these files should have been corrected in the repo (i.e. no floating points on quantiles anymore) but may not have been updated in Zoltar? 

There are some other missing interval scores for other models as well in places where I don't think they should be missing, but this was the easy one to document.

**Comment by matthewcornell** [comment]
I ran all scores locally against the latest hub version of 2020-05-04-MIT_CovidAnalytics-DELPHI.csv , using the latest truth, and found no empty cells in the result. I'm thinking zoltar hasn't been updated fully yet?

![Screen Shot 2020-05-13 at 10 59 18 AM](https://user-images.githubusercontent.com/1034007/81829543-ffac9980-9508-11ea-98c1-01be3bb54b8b.png)

**Comment by Khoale1096** [comment]
The latest score CSV on Zoltar seems to resolve this now. @nickreich Please let us know if we miss any model?
![Screenshot (390)](https://user-images.githubusercontent.com/31902663/81837568-050ee180-9513-11ea-9015-4614ed52f2f4.png)
