### ISSUE TITLE
resolve issue of duplicate forecasts in COVID-19 Forecasts project

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#224]
@elray1 caught this at https://app.slack.com/client/T089JRGMA/C011SKXLBA8/thread/C011SKXLBA8-1592275228.041500 : "It looks like we have ended up with duplicated forecasts for SWC-TerminusCM in Zoltar."

We need to:
- [ ] determine the cause of the duplication - @Khoale1096 
- [ ] resolve it going forward - @matthewcornell  @Khoale1096 
- [ ] delete the duplicates - @matthewcornell

**Comment by matthewcornell** [comment]
@elray1 script to verify:

```r
library(zoltr)
zoltar_connection <- new_connection(Sys.getenv("Z_HOST"))
zoltar_authenticate(zoltar_connection, Sys.getenv("Z_USERNAME"), Sys.getenv("Z_PASSWORD"))
project_url <- "https://www.zoltardata.com/api/project/44/"

list_query <- list(
  model_abbrs = list("SWC-TerminusCM"),
  types = list("quantile"),
  timezeros = list("2020-06-15"),
  targets = list("1 wk ahead cum death")
)
zoltar_query <- zoltr::query_with_ids(zoltar_connection, project_url, list_query)
job_url <- zoltr::submit_query(zoltar_connection, project_url, zoltar_query)

# Poll job

all_forecasts <- job_data(zoltar_connection, job_url)
any(duplicated(all_forecasts))
all_forecasts[1,]
all_forecasts[1174,]
identical(all_forecasts[1,], all_forecasts[1174,])

```

**Comment by Khoale1096** [comment]
Update: no duplicates is found on Zoltar as of 2/3/2021.

**Comment by Khoale1096** [comment]
Closing this issue since no duplicates is found after the GitHub Action that performs Zoltar upload every 6 hours is implemented. This implied that this sequential process has resolved the race condition issue which gave rise to the duplicates
