### ISSUE TITLE
review current scoring design and implementation

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#246]
Nightly runs take what feels to @nickreich a long time (currently ~90 minutes). We have a hunch that this could be sped up with more data science-y solution (say using data frames). Ideally the solution would also use less RAM. We should review the current implementation's data models and algorithms to evaluate opportunities for improvement via redesign.

**Comment by nickreich** [comment]
should we close this issue now that we have reviewed scoring design?

**Comment by matthewcornell** [comment]
After our review we decided to move scoring out of Zoltar proper to its libraries. This will simplify our code and architecture b/c we will no longer pre-compute and store scores, something that would not scale given #273 .
