### ISSUE TITLE
understand why metadata is not present for some forecasts

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#257]
Metadata is not present for two forecasts:

- LANL-GrowthRate 2020-09-14: https://www.zoltardata.com/forecast/13232
- CU-select 2020-09-13: https://www.zoltardata.com/forecast/13227

This seems to be b/c those two forecasts failed to upload on 9/14 (they hit timeout - 500 sec) but empty forecasts were left in the database (a bug that I will fix soon).

Questions:
- Why did these time out?
- Have we re-uploaded them?
- What other forecasts have zero predictions?

**Comment by Khoale1096** [comment]
Update: The forecasts are re-uploaded and it seems to be ok now https://zoltardata.com/forecast/13248 and https://zoltardata.com/forecast/13247
