### ISSUE TITLE
add link back to Zoltar homepage in docs menu

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#264]
Right now, there is no obvious link when on a random docs page, to get back to the Zoltar homepage.

![image](https://user-images.githubusercontent.com/1280767/95146416-c12fa980-074b-11eb-9ac3-51586fedc84d.png)

**Comment by nickreich** [comment]
Maybe above the "Zoltar Documentation" boldface section in the nav menu, we could have a "Zoltar main site" link, or something similar?

**Comment by matthewcornell** [comment]
closed by https://github.com/reichlab/docs.zoltardata/commit/d12633f39c7e0ecf2767ce74272578580b7d1a35
