### ISSUE TITLE
Downloading Project truth for "COVID-19 Forecasts" times out

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#277]
https://www.zoltardata.com/project/44/truth

I suggest we move from downloading one big file to querying truth similar to how we download forecasts and scores. Alternatively we can cache the creation of truth as a stop-gap, but coding that may not be much less work than the former.

**Comment by matthewcornell** [comment]
Tagging @nickreich and @elray1 re: priority.

**Comment by nickreich** [comment]
I'm ok doing this as a query. is the downloading failing everywhere? or just when downloading from one particular method?

**Comment by matthewcornell** [comment]
I don't have details, but downloading from the web seems to be failing frequently. It will take time to research.

**Comment by matthewcornell** [comment]
Closing b/c we replaced truth with querying: #254
