### ISSUE TITLE
Unable to make connection to Zoltar in R

### ISSUE THREAD

**Issue by swads96** [reichlab/forecast-repository#291]
I'm trying to load data from the COVID-19 forecast hub onto my personal machine. To make the connection to Zoltar I run

library(zoltr)
zoltar_connection <- new_connection()
zoltar_authenticate(zoltar_connection, Sys.getenv("Z_USERNAME"), Sys.getenv("Z_PASSWORD"))
zoltar_connection

but I get the error

get_token(): POST: https://zoltardata.com/api-token-auth/
Error in get_token(self) : Bad Request (HTTP 400).

**Comment by matthewcornell** [comment]
Hi. Sorry you're having trouble. Are you setting the two environment variables to your account's information? Also, are you using the latest version in github, not the CRAN one? Thanks --matt

----
Matthew Cornell, M.S. ( cornell@umass.edu | 413-626-3621 )
Senior Research Software Engineer
Department of Biostatistics and Epidemiology
School of Public Health & Health Sciences
UMass Amherst


________________________________

**Comment by swads96** [comment]
I installed the github version with

install.packages("devtools")
devtools::install_github("reichlab/zoltr", force=TRUE)

And yes I used the username and password that I have to log in to Zoltar.
________________________________

**Comment by matthewcornell** [comment]
I wonder if it's an environment variable issue. Others have had trouble getting R to access them properly. 

If you run `Sys.getenv()`, do you see the two environment variables and their values? And are those values the ones you use to log into https://www.zoltardata.com/ ?

Let me know the date and time to the minute that you next try it, OK? I'll see if there's anything in the logs.

**Comment by swads96** [comment]
There are a number of environment variables that I can see, but none of them match what I use to login to zoltardata.com.

I just ran this code again

devtools::install_github("reichlab/zoltr", force=TRUE)
library(zoltr)
zoltar_connection <- new_connection()
zoltar_authenticate(zoltar_connection, Sys.getenv("spencerw"), Sys.getenv("4Y2@#ai@TITW"))

It was run at 3/10/21 3:49:11 CST
________________________________

**Comment by matthewcornell** [comment]
Sorry I wasn't clear. The environment variables must be accessible to R in order for you to connect to zoltar. The commands `Sys.getenv("Z_USERNAME")` and `Sys.getenv("Z_PASSWORD")` get your username and password from the environment and pass them to zoltar. 

The code you pasted is incorrect (plus it shows your account info here publicly, so you should delete yoru comment. But I like your idea. Instead you should try passing the actual values you pasted above:

```
devtools::install_github("reichlab/zoltr", force=TRUE)
library(zoltr)
zoltar_connection <- new_connection()
zoltar_authenticate(zoltar_connection, "spxxx", "4Yxxx")
```

Let us know.

**Comment by swads96** [comment]
Oh I see. When I run Sys.getenv("Z_USERNAME") it returns a blank string. But when I just enter my username and password strings directly into zoltar_authenticate(), it looks like the connection is made just fine.
________________________________

**Comment by matthewcornell** [comment]
Makes sense. Most people find it convenient (and safer) to use the environment variable feature as mentioned here: http://reichlab.io/zoltr/articles/getting-started.html#setting-up-your-account:

> Once you have an account, we recommend storing your Zoltar username and password in your .Renviron file. In practice this means having a file named .Renviron in your home directory. (You can read more about R and environment variables here: https://db.rstudio.com/best-practices/managing-credentials/#use-environment-variables .)

**Comment by swads96** [comment]
Great that helped me get things working thanks!

Can I just get your help on downloading a .csv for a forecast from the COVID-19 hub? I'm struggling figuring out how to do that. I'm trying to use the forecast_data_from_cdc_csv_file() function, but I'm not sure what arguments to put in for the forecast I want.

Thanks
________________________________

**Comment by swads96** [comment]
Nevermind, I got it working. Thanks!
________________________________
