### ISSUE TITLE
data_frame_from_forecast_data() function not found

### ISSUE THREAD

**Issue by wadspen** [reichlab/forecast-repository#331]
I have been using the zoltr package for months now with no problems until I just started getting this error when calling the 
data_frame_from_forecast_data() function.

Error in data_frame_from_forecast_data(model_forecast_data) : 
  could not find function "data_frame_from_forecast_data"

The other zoltr functions seem to be working just fine. 
I just installed R version 4.1.2 and RStudio 2022.02.0. I'm wondering if this is part of what's causing the issue? I also tried reinstalling zoltr, but that didn't resolve the issue.

**Comment by matthewcornell** [comment]
Hi @swads96 . I'm sorry you're having trouble. I looked back at the log and unfortunately I do not see any changes to that function or to related files. We are not updating CRAN, so you should be installing the GitHub version as described at https://github.com/reichlab/zoltr :

```R
install.packages("devtools")
devtools::install_github("reichlab/zoltr")
```

Would you please try reinstalling? If you're still getting the error, you should send us the commands you're running o we can try to recreate the problem. Thanks.

**Comment by nickreich** [comment]
Closing due to no follow-up.
