### ISSUE TITLE
Add a feature to decide which target groups are included by default

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#347]
Per @nickreich 's comment on slack:
> Another question this raises for me is whether the visualization for a given project will list all target groups by default? For the COVID hub, for example, we might not want to display “day ahead inc deaths” because forecasts for that target haven’t been made in over 2 years. Or for the election forecasts project, it might make sense to not have a visualization at all, given the structure of the particular targets. So I guess I’m proposing a somewhat low-priority todo for the viz to be to have (in the viz configuration file?) a list of targets to filter on, and if these don’t match any target groups in the project, then there is no viz for that project. Or something similar?
> ...
> For many of the targets we don’t have any truth data (e.g. day ahead incident hospitalizations, for one) or any/many forecasts (day ahead cumulative deaths, for one).

**Comment by nickreich** [comment]
In Zoltar, the suggestion might be to add a field to the viz config that specifies which fields should be included in the viz? Or, 
```
    "initial_target_var": "week_ahead_incident_deaths",
```
could be instead something like
```
    "included_target_vars": ["week_ahead_incident_deaths", "day_ahead_incident_hosps", ...],
```
where the first item is what is loaded by default?
