### ISSUE TITLE
create new prediction_types for mean and median

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#367]
To try to bring Zoltar closer to our current thinking about how to represent point forecasts, we should add `mean`, `median`, and perhaps `mode` to the list of valid prediction types. However, this raises a question of what target_types are valid for each of these new prediction_types.

This is the current table [from Zoltar](https://docs.zoltardata.com/targets/#valid-prediction-types-by-target-type):
![image](https://github.com/reichlab/forecast-repository/assets/1280767/88747ac9-ac4c-4363-b9bb-3d8f2f9e1ae3)

- continuous, discrete and date target types: all three are valid options.
- nominal: only valid for mode (mean and median are numeric operations that don't apply to nominal outcomes)
- binary: only valid for mode and median 
    - the data_type for a binary prediction is boolean, therefore a mode and median mean the same thing in this context: the value (0 or 1) that appears more often in a vector of 0s and 1s
    - a mean would imply a continuous value between 0 and 1. if a probability were desired as the outcome, then a continuous target type would be used with limits of 0 and 1.

tagging @elray1 and @annakrystalli for additional input.

**Comment by nickreich** [comment]
Noting that the idea here would be to 
1. add `mean`, `median` and perhaps `mode` prediction types to zoltar, leaving `point` prediction type as legit for legacy projects.
2. make it so that new projects cannot use `point` target types.
3. as a later task, consider migrating some point data to the other new prediction types.

Noting that this is related to https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/54

**Comment by matthewcornell** [comment]
Capture this as a table: This will be the new "Valid prediction types by target type" table:

![image](https://github.com/reichlab/forecast-repository/assets/1034007/5d43feb4-f921-44dd-8063-fd4db3364694)

**Comment by matthewcornell** [comment]
Around [this line](https://github.com/reichlab/forecast-repository/blob/d39322234b94b93921a081482fb60cd03781d6c7/utils/project_truth.py#L229) in the function `_load_truth_data()` shows that we use 'point' for the prediction dictionary data that generated from incoming truth rows. Since we are retiring point types, how do we handle/represent truth with our three point replacements (mean, median and perhaps mode)?

**Comment by nickreich** [comment]
@matthewcornell The table looks correct to me.

Your question about representation of truth data is a good one. Given that truth data are a separate kind of data stored in Zoltar, I'm not sure it really matters what type we store them as. Honestly, we could keep them stored as "point", and have them be the only thing that could use that prediction type? Or we could just pick one of "mean", "median" or "mode" and use that from here on out? (would that leave backwards compatibility issues for truth data stored in a certain way in the system now?) I'm imagining that we might need to pick one prediction type and store all truth data in the system as that type? Maybe for that reason we should choose "mode" as it is valid for all target types, as is "point"?

**Comment by matthewcornell** [comment]
@nickreich WRT the underlying truth representation ("point" vs. ...) I don't think there will be an external impact (queries come back as CSV with a catch-all 'value' column for "point" and - with this change - the other three), so I'm ok staying with "point" or switching to "mode". I suggest we use the latter so that we are moving away from "point". Yes, that will mean old truth data is "point" and new is "mode", but we can change the former to latter if/when we do your point #3 above.

**Comment by matthewcornell** [comment]
We will need to review constraints specified in https://docs.zoltardata.com/validation/ - which apply to the three new types? E.g., are they the same as point?

**Comment by matthewcornell** [comment]
We will need to review conversions for the three new types here: https://docs.zoltardata.com/forecastqueryformat/#automatic-prediction-type-conversion . Again, same as point?

**Comment by nickreich** [comment]
The [Point prediction elements](https://docs.zoltardata.com/validation/#point-prediction-elements) constraints could be the same for mean, median and mode. 

In the [Tests for Prediction Elements by Target Type](https://docs.zoltardata.com/validation/#tests-for-prediction-elements-by-target-type) section, I think all of the uses of "point" prediction type could just be replaced by the "mean, median, and mode" types. 

We want the same functionality, validation and constraints for the three new types as we had for point.

The conversions also seem more or less straight forward. My suggestion might be to aspirationally support the following conversions:
```
mean <- named, sample
median <- named, sample
mode <- named
```
I intentionally left out the conversion of sample -> mode as there could be complications here for continuous outcomes. So I vote for just leaving it off for now.

And I see that we have some existing conversions supported 
> conversions: point <- sample (uses either [statistics.mean()](https://docs.python.org/3/library/statistics.html#statistics.mean) or [statistics.median()](https://docs.python.org/3/library/statistics.html#statistics.median) depending on the convert.point option)

Which I think could just be translated as the functions to convert from sample to mean and median types.

**Comment by matthewcornell** [comment]
I'm making progress, but I think it will be clean to do this via three implementation phases:

- phase one: **add the three new types**. keep the point type
- phase two: **depreciate the point type**. disable it for new forecasts. change `_load_truth_data()` from "point" to "mode". replace it in tests with mode. do not convert existing forecasts
- phase three: **retire the point type**. remove it from the database and code. convert existing forecasts from point to mode


Thoughts?

**Comment by matthewcornell** [comment]
Status (">>" is current):

- [ ] >> phase one: **add the three new types**. keep the point type
- [ ] phase two: **depreciate the point type**. disable it for new forecasts. change _load_truth_data() from "point" to "mode". replace it in tests with mode. do not convert existing forecasts
- [DEC: no] phase three: **retire the point type**. remove it from the database and code. convert existing forecasts from point to mode

**Comment by matthewcornell** [comment]
@nickreich , in [this section](https://docs.zoltardata.com/forecastqueryformat/#automatic-prediction-type-conversion) of the docs, I think # 1 should say "convert FROM" instead of "convert TO", agreed?:

> Auto-conversion is activated via two query parameters:
> 1. Specify the forecast types (# 5 above) that you want the program to convert TO (the default, if unspecified is all types).
> 2. Include query options for the conversions you want. Including an option does two things: a) it tells Zoltar that it should convert TO that type (i.e., that conversion is activated), and b) possible details about how to do the conversion.

**Comment by nickreich** [comment]
@matthewcornell I'm confused about what the "automatic conversion" means. Are some predictions converted automatically? do we specify whether or not they are converted somewhere? Could you point to an example in Zoltar where this is happening (or configured) currently?

**Comment by matthewcornell** [comment]
- I agree that "auto" is misleading; it should just be "conversion".
- Conversion happens at the user's explicit request via [query options](https://docs.zoltardata.com/forecastqueryformat/#query-options). For example, `{... "options": {"convert.mean": true}}` ("convert.mean" is a new option).

**Comment by nickreich** [comment]
Regarding your question about FROM vs. TO, I just don't have enough of a sense from the documentation what is actually happening with the conversion to answer your question. Maybe we should just try to re-write that part of the documentation to more clearly reflect the action that is being taken?

**Comment by matthewcornell** [comment]
@nickreich [Zoltpy](https://github.com/reichlab/zoltpy) provides the (somewhat experimental) feature of bulk import/export specified in this issue: [[investigate support of bulk zoltar queries #321]](https://github.com/reichlab/forecast-repository/issues/321) - [docs here](https://docs.zoltardata.com/forecasts/#download-the-zoltar-database-for-local-use-beta). IIRC Martha tried using it and it wasn't viable (maybe due to trouble accessing Python via R?), and so my question is whether it's worth my updating that part of the code to use the current issue's new prediction types. I suggest we remove the code from both zoltpy and the server unless we think we'll use it again. Thoughts?

**Comment by nickreich** [comment]
I could maybe see us using this again at some point in the future, but I agree that it feels vestigial at this point and could be removed for now.
