### ISSUE TITLE
Truth data not showing up in viz

### ISSUE THREAD

**Issue by lshandross** [reichlab/forecast-repository#371]
The [visualization](https://zoltardata.com/project/360/viz) is not showing any truth data for any timezeros, though the forecasts are showing up just fine. I've attached the code I used to re-format the truth data and forecasts from the original files [this repo](https://github.com/cdcepi/FluSight-forecast-hub), as well as a few example truth CSVs. 

I've tried a number of different fixes to see if changing information within the truth CSVs would make the truth data visible in the visualization but none of these methods worked:

- Uploaded truth data both using `zoltr` and the web page form
- Tried using different horizons associated with the targets (e.g., "-1 wk inc flu hosp", "0 wk inc flu hosp", "1 wk inc flu hosp" as well as the same for the wk flu hosp rate change target)
- Tried uploading truth data only for the "wk inc flu hosp" target in case there was an issue with the value column being a character type

Note that when I try to query the truth from the web page form, it returns exactly what I uploaded, so I can't seem to diagnose what the problem is.

[CDC_FluSight_Forecast_Hub-config.json](https://github.com/reichlab/forecast-repository/files/13549380/CDC_FluSight_Forecast_Hub-config.json)
[flusight_truth_upload.txt](https://github.com/reichlab/forecast-repository/files/13550417/flusight_truth_upload.txt)
[flusight_forecast_upload.txt](https://github.com/reichlab/forecast-repository/files/13550418/flusight_forecast_upload.txt)
[flusight_truth_format.txt](https://github.com/reichlab/forecast-repository/files/13550419/flusight_truth_format.txt)
[flusight_forecast_format.txt](https://github.com/reichlab/forecast-repository/files/13550420/flusight_forecast_format.txt)
[truth_inc-hosp_2023-11-18_both-targets.csv](https://github.com/reichlab/forecast-repository/files/13551424/truth_inc-hosp_2023-11-18_both-targets.csv)
[truth_inc-hosp_2023-11-18_inc-hosp-only.csv](https://github.com/reichlab/forecast-repository/files/13551425/truth_inc-hosp_2023-11-18_inc-hosp-only.csv)

**Comment by matthewcornell** [comment]
Looking at the attached files, what steps should I take in what order to recreate the project on my local machine? Apologies if it should be obvious...

**Comment by nickreich** [comment]
I think this can be closed now?
