### ISSUE TITLE
certification problem when loading docs

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#373]
<img width="997" alt="image" src="https://github.com/reichlab/forecast-repository/assets/1280767/baa98c77-2bef-4336-8ce0-b1cf74308159">

**Comment by matthewcornell** [comment]
I found it last night and was just starting to look into it. Thanks.

**Comment by matthewcornell** [comment]
Fixed thanks to response on [this thread](Custom domain SSL/TLS certificate error: Acme::Client::Error::Malformed: JWS header parameter 'url' incorrect - Support - Netlify Support Forums
https://answers.netlify.com/t/custom-domain-ssl-tls-certificate-error-acme-jws-header-parameter-url-incorrect/110665/3):

> I’m showing that your CNAME Record for docs.zoltardata.com is pointing to docs-zoltardata.netlify.com instead of docs-zoltardata.netlify.app (the difference is at the end for .com instead of .app). Could you try changing the CNAME Record to docs-zoltardata.netlify.app and see if that resolves the issue?
>
> After changing the record and it propagates, click on the Renew certificate button on this page:
[app.netlify.com](https://app.netlify.com/sites/docs-zoltardata/domain-management#ssl-tls-certificate)

I asked for ideas re: what changed that might have caused this.
