### ISSUE TITLE
Actual plot for Impetus data set is missing some values

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#80]
Looking at the visualizations page for the 'Impetus Province Forecasts' project, the 'actual' is blank at some points around Feb 18. We think the truth data file does not include lines when values are zero. Also, maybe the D3 Foresight component has an issue showing zeros?

<img width="211" alt="screen shot 2018-06-26 at 10 19 32 am" src="https://user-images.githubusercontent.com/1034007/41918555-9b12f024-792a-11e8-9e6e-069cf132379c.png">

<img width="217" alt="screen shot 2018-06-26 at 10 19 25 am" src="https://user-images.githubusercontent.com/1034007/41918556-9b279a56-792a-11e8-9833-15a857e06c5e.png">

**Comment by katiehouse3** [comment]
Also added an issue to the dengue data import to hopefully address the truth table omitting zero values. https://github.com/reichlab/dengue-data/issues/83

**Comment by matthewcornell** [comment]
I'm widening this out to include a handful of Impetus project plot-related issues, which are likely interconnected:
1. the 'actual' is blank at some points around Feb 18 (this original issue)
1. #82
1. some step ahead targets are not shown in the popup, such as in the second image above
1. the first point should be labelled "1 ahead", the second "2 ahead", etc. however, the only labeled step ahead target is the second point, which is incorrectly labelled "1 ahead" instead of "2 ahead"

**Comment by lepisma** [comment]
About 1. `blank` means something like `[1.2, 1.3, null, 1.1, 1.3 ...]` ? If yes, then one explanation can be because of the way we handle the actual series. We expect a single continuous chunk of non-null values in the series. The behavior with intermittent `nulls` is unspecified.

I can make it handle this case but am not sure if missing actual values are truly non-bugs on the data side.

**Comment by matthewcornell** [comment]
![image](https://user-images.githubusercontent.com/1034007/42762989-c8782358-88df-11e8-8935-b8ffdce62bbc.png)

**Comment by matthewcornell** [comment]
@lepisma I slacked you an account to use to access https://reichlab-forecast-repository.herokuapp.com/project/5/visualizations for #3 above. let me know how it goes

**Comment by lepisma** [comment]
I see the issue. Firstly, the `nulls` in actual is make the details of actual hidden in popup (which is obvious). Next, values of 0.0 are getting picked as falsy so the tooltip takes the first non-zero value as the 1-ahead prediction and goes from there, skipping everything 0.0 prediction.

Made an issue on d3-foresight [here](https://github.com/reichlab/d3-foresight/issues/60).

**Comment by lepisma** [comment]
Try v0.9.9 (https://unpkg.com/d3-foresight@0.9.9/dist/d3-foresight.min.js) for d3-foresight. Should fix the tooltip issues.

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Visualization in Zoltar is currently disabled. Prioritization is up to @nickreich .
