### ISSUE TITLE
Consider not storing bin rows with zero values

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#84]
This issue captures this thread from @nickreich - https://reichlab.slack.com/archives/C57HNDFN0/p1530301398000249

---- [nick]
@cornell We talked today about making what we think are minor modifications to the forecast format for the impetus forecasts, but that could possibly have implications for a more general set of changes. Do you foresee any problems with these suggested changes?
1. we will change bin boundary definitions for the impetus forecasts. Specifically, we would like to change so that every bin has width 1.
2. to accommodate this size-wise, we'd like to have the option of removing from storage any rows of the `.cdc.csv` files that have `type=="bin"` and `value==0`.

---- [matt]
I looked at a data file -> questions:

1. I see many bin values are 0, and those that aren't sum to 1.0. Is this what you mean by "bin width 1?"
2. Does this filtering happen at the time of import, or is it new manually-activated feature (a project button, say)?
3. Is this an Impetus-specific feature, or would it be useful to other projects?
4. Does this need to be validated at import time?
5. Are there other categories of filtering like this that we may want to implement in the future?

---- [nick]
By binwidth=1 I mean that the `bin_end - bin_start` would always =1. right now, in impetus project, many bin sizes are about 10, so we would have almost a 10x increase in storage needs if we were to only implement (1) without implementing (2). (numbering referring to my original post).

Re: your question 2: I was imagining this would happen prior to importing, but you could also run a check within Zoltar to save storage rows. More generally (responding to Q3), not storing rows that contain zero data might be a reasonable way to save space in all projects.

Q4: it could be checked at import time, but I don't see it as __necessary__ to have all zero rows removed from imports.

Q5: not sure.

---- [matt]
ok, this needs to be talked out some more. if we decide to not store those zero rows then recreating the data (say for download) will have more steps, e.g., inferring missing bins

also, other functions that depend on all bins being present will need to accommodate the missing rows.

**Comment by matthewcornell** [comment]
After talking with @nickreich today we decided:
1. The Impetus export program will change exported bin widths to 1 (which will result in many rows where type=="bin" and value==0), and will only generate non-zero bin rows in the .cdc.csv files.
2. Point 1 should not impact current Zoltar features, mainly scoring, b/c only "point" rows are used.
3. Zoltar will not import rows where type=="bin" and value==0. This is solely a storage optimization.
4. Point 3 means Zoltar's export features (CSV and JSON formats) will *not* include those skipped rows. Thus, the exported CSV files will not be identical to the imported ones. We can fix this later if it becomes important.

**Comment by matthewcornell** [comment]
An issue: Forecasts are validated against the project's template, and this includes checking that the list of bin_start_incl and bin_end_notincl are equal. If bins with zero values are omitted from the forecast file then the validation will fail. One solution is to verify that the forecast bins are a /subset/ of the template ones.

**Comment by nickreich** [comment]
That seems like a good solution to me. combined with a check about whether the bin values sum to 1, we should have our bases covered.

**Comment by matthewcornell** [comment]
Great. It should be straightforward to implement this, and I see that it will save 30% space in our current databases.
