### ISSUE TITLE
Update d3 component to never show TimeZero line

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/forecast-repository#92]
- https://github.com/reichlab/d3-foresight/issues/57#issuecomment-410547564
- version 0.10.1: https://www.npmjs.com/package/d3-foresight
- http://reichlab.io/d3-foresight/#timechart-dvt
  options parameter > timezeroLine: true

**Comment by mzorn-58** [comment]
@matthewcornell Can this be closed or archived?

**Comment by matthewcornell** [comment]
Visualization in Zoltar is currently disabled. Prioritization is up to @nickreich .
